version: '2'

services:
  code-api:
    restart: always
    build: .
    env_file: .env
    network_mode: "host"
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

    command: 'python3.11 main.py'

