"""add task_id

Revision ID: a5811e89b070
Revises: e1c95338a6aa
Create Date: 2023-04-10 16:46:46.663261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5811e89b070'
down_revision = 'e1c95338a6aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verdicts', sa.Column('task_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'verdicts', ['task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'verdicts', type_='unique')
    op.drop_column('verdicts', 'task_id')
    # ### end Alembic commands ###
