"""init

Revision ID: e1c95338a6aa
Revises: 
Create Date: 2023-04-10 16:39:14.688007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c95338a6aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verdicts',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verdicts')
    # ### end Alembic commands ###
